<a href="https://colab.research.google.com/github/Moulika-tata/AI-ML-Engineer-90-Days/blob/main/Day_03_NumPy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 3 — NumPy Practice

## Topics to Learn
- NumPy Broadcasting
- Aggregation Functions
- Axis: `axis=0` and `axis=1`
- Random Data Generation
- Array Slicing
- Boolean Filtering
- Array Reshaping
- Vectorized Operations

## Learning Objectives
- Perform numerical operations using NumPy.
- Calculate sum, mean, minimum, maximum, standard deviation, and variance.
- Understand row-wise and column-wise operations.
- Generate random numbers and reshape arrays.
- Solve numerical problems without Pandas.

In [55]:
#Import NumPy and create an array

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)


Array: [10 20 30 40 50]
Shape: (5,)
Dimensions: 1
Size: 5
Data type: int64


## Vectorized Operations

Vectorization allows NumPy to perform operations on an entire array without using an explicit loop.

Examples:
- Addition
- Subtraction
- Multiplication
- Division

In [56]:

arr = np.array([10, 20, 30, 40, 50])

print("Addition:", arr + 5)
print("Subtraction:", arr - 5)
print("Multiplication:", arr * 2)
print("Division:", arr / 10)


Addition: [15 25 35 45 55]
Subtraction: [ 5 15 25 35 45]
Multiplication: [ 20  40  60  80 100]
Division: [1. 2. 3. 4. 5.]


## Aggregation Functions

Aggregation functions summarize numerical data.

- `np.sum()` — calculates the total.
- `np.mean()` — calculates the average.
- `np.min()` — finds the minimum value.
- `np.max()` — finds the maximum value.
- `np.std()` — calculates standard deviation.
- `np.var()` — calculates variance.

In [57]:

arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Standard deviation:", np.std(arr))
print("Variance:", np.var(arr))


Sum: 150
Mean: 30.0
Minimum: 10
Maximum: 50
Standard deviation: 14.142135623730951
Variance: 200.0


## Array Slicing

Slicing extracts a portion of an array.

Syntax: `array[start:stop]`

- The start index is included.
- The stop index is excluded.
- Python indexing begins at zero.

In [58]:

arr = np.array([5, 10, 15, 20, 25, 30])

print("First three elements:", arr[:3])
print("Elements at indices 1 to 3:", arr[1:4])
print("Last three elements:", arr[-3:])


First three elements: [ 5 10 15]
Elements at indices 1 to 3: [10 15 20]
Last three elements: [20 25 30]


## Boolean Filtering

Boolean filtering selects elements that satisfy a condition.

- `arr > 30` selects values greater than 30.
- `arr < 30` selects values less than 30.
- `&` combines multiple conditions using AND.
- Each condition must be enclosed in parentheses when using `&`.

In [59]:

arr = np.array([12, 25, 38, 45, 60, 67, 75])

print("Values greater than 40:", arr[arr > 40])
print("Values less than 50:", arr[arr < 50])
print("Values between 40 and 70:", arr[(arr > 40) & (arr < 70)])


Values greater than 40: [45 60 67 75]
Values less than 50: [12 25 38 45]
Values between 40 and 70: [45 60 67]


## NumPy Broadcasting

Broadcasting allows NumPy to perform operations between arrays with compatible shapes.

Examples:
- Adding a scalar to every element.
- Adding a one-dimensional array to each row of a compatible two-dimensional array.

In [60]:

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matrix + 5:")
print(matrix + 5)

values = np.array([10, 20, 30])

print("Matrix + values:")
print(matrix + values)


Matrix + 5:
[[ 6  7  8]
 [ 9 10 11]]
Matrix + values:
[[11 22 33]
 [14 25 36]]


## Understanding Axis

For a two-dimensional NumPy array:

- `axis=0` performs operations down the rows, producing one result per column.
- `axis=1` performs operations across columns, producing one result per row.

Examples:
- `np.sum(arr, axis=0)` calculates column totals.
- `np.mean(arr, axis=1)` calculates row averages.

In [61]:

marks = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 78]
])

print("Column totals (axis=0):")
print(np.sum(marks, axis=0))

print("Column averages (axis=0):")
print(np.mean(marks, axis=0))

print("Row totals (axis=1):")
print(np.sum(marks, axis=1))

print("Row averages (axis=1):")
print(np.mean(marks, axis=1))


Column totals (axis=0):
[218 247 253]
Column averages (axis=0):
[72.66666667 82.33333333 84.33333333]
Row totals (axis=1):
[240 220 258]
Row averages (axis=1):
[80.         73.33333333 86.        ]


## Random Data Generation

NumPy provides functions to generate random data.

- `np.random.rand()` generates random floating-point numbers between 0 and 1.
- `np.random.randint()` generates random integers.
- The upper bound of `np.random.randint()` is excluded.
- `size` specifies the number or shape of generated values.

In [62]:

# Generate 5 random floating-point numbers
print("Random floats:")
print(np.random.rand(5))

# Generate 10 random integers from 1 to 100
random_numbers = np.random.randint(1, 101, size=10)
print("Random integers:")
print(random_numbers)

# Generate a 3x4 random matrix
random_matrix = np.random.randint(10, 51, size=(3, 4))
print("Random matrix:")
print(random_matrix)

print("Shape:", random_matrix.shape)
print("Mean:", np.mean(random_matrix))


Random floats:
[0.61748151 0.61165316 0.00706631 0.02306243 0.52477466]
Random integers:
[42 92 60 80 15 62 62 47 62 51]
Random matrix:
[[12 46 16 30]
 [18 48 27 13]
 [34 23 18 35]]
Shape: (3, 4)
Mean: 26.666666666666668


## Array Reshaping

The `reshape()` method changes an array's dimensions without changing its elements.

The new shape must contain the same total number of elements as the original array.

In [63]:

arr = np.arange(1, 7)

print("Original array:")
print(arr)

reshaped = arr.reshape(2, 3)

print("Reshaped array:")
print(reshaped)

print("Shape:", reshaped.shape)


Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


## Combined Numerical Practice

In this task, we combine aggregation, filtering, and axis operations.

Objectives:
1. Calculate row totals.
2. Calculate column averages.
3. Select values greater than 35.

This task reinforces the main NumPy concepts covered on Day 3.

In [64]:

arr = np.array([
    [15, 20, 25],
    [30, 35, 40],
    [45, 50, 55]
])

print("Row totals:", np.sum(arr, axis=1))
print("Column averages:", np.mean(arr, axis=0))
print("Values greater than 35:", arr[arr > 35])


Row totals: [ 60 105 150]
Column averages: [30. 35. 40.]
Values greater than 35: [40 45 50 55]


# Day 3 Summary — NumPy Practice

## Concepts Learned
- Array properties and vectorized operations
- Aggregation functions
- Array slicing and Boolean filtering
- Broadcasting
- `axis=0` and `axis=1`
- Random data generation
- Array reshaping

## Practice Completed
- Completed 10 numerical NumPy practice tasks.
- Completed the 10-question timed assessment.

## Assessment Result
- Score: 9/10
- Percentage: 90%

## Key Takeaway
NumPy provides efficient tools for numerical computing and forms an important foundation for data analysis and machine learning.