<a href="https://colab.research.google.com/github/Moulika-tata/AI-ML-Engineer-90-Days/blob/main/Day_02_NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 2 — NumPy Fundamentals for AI/ML

Today I learned the fundamentals of NumPy and practiced arrays, indexing,
slicing, vectorized operations, broadcasting, reshaping, statistical
functions, and filtering.

## 1. What is NumPy?

NumPy is a Python library used for numerical computing.

It provides powerful array structures and efficient mathematical operations.

NumPy is widely used in:
- Artificial Intelligence
- Machine Learning
- Data Science
- Deep Learning

NumPy arrays are generally more suitable than normal Python lists for
numerical and mathematical operations.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


## 2. NumPy Array Properties

Important NumPy array properties:

- shape → tells us the number of rows and columns
- ndim → tells us the number of dimensions
- size → tells us the total number of elements
- dtype → tells us the data type of the elements

In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Array:")
print(arr)

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Array:
[[10 20 30]
 [40 50 60]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64


## 3. Indexing

Indexing is used to access individual elements of an array.

Python and NumPy use zero-based indexing.

Therefore:
- First element → index 0
- Second element → index 1
- Third element → index 2

For a 2D array, we use:

array[row, column]

In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Element at row 0, column 0:", arr[0, 0])
print("Element at row 0, column 1:", arr[0, 1])
print("Element at row 1, column 0:", arr[1, 0])
print("Element at row 1, column 2:", arr[1, 2])

Element at row 0, column 0: 10
Element at row 0, column 1: 20
Element at row 1, column 0: 40
Element at row 1, column 2: 60


In [ ]:
print("Last element:", arr[-1, -1])
print("Second last column of last row:", arr[-1, -2])

Last element: 60
Second last column of last row: 50


## 4. Slicing

Slicing is used to access multiple elements from an array.

Basic syntax:

array[start:stop]

The start index is included and the stop index is excluded.

For a 2D array:

array[row_start:row_stop, column_start:column_stop]

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("Elements from index 1 to 3:", arr[1:4])
print("First three elements:", arr[:3])
print("Elements from index 2:", arr[2:])
print("Reverse array:", arr[::-1])

Elements from index 1 to 3: [20 30 40]
First three elements: [10 20 30]
Elements from index 2: [30 40 50]
Reverse array: [50 40 30 20 10]


In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("First two rows:")
print(arr[:2])

print("Second column:")
print(arr[:, 1])

print("First two columns:")
print(arr[:, :2])

print("Rows 1 onward and columns 1 onward:")
print(arr[1:, 1:])

First two rows:
[[10 20 30]
 [40 50 60]]
Second column:
[20 50 80]
First two columns:
[[10 20]
 [40 50]
 [70 80]]
Rows 1 onward and columns 1 onward:
[[50 60]
 [80 90]]


## 5. Vectorized Operations

Vectorization allows NumPy to perform operations on an entire array
without manually writing a loop for every element.

Examples:
- Addition
- Subtraction
- Multiplication
- Division
- Power
- Comparisons

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("Original:", arr)
print("Add 5:", arr + 5)
print("Subtract 5:", arr - 5)
print("Multiply by 2:", arr * 2)
print("Divide by 10:", arr / 10)
print("Square:", arr ** 2)
print("Greater than 25:", arr > 25)

Original: [10 20 30 40 50]
Add 5: [15 25 35 45 55]
Subtract 5: [ 5 15 25 35 45]
Multiply by 2: [ 20  40  60  80 100]
Divide by 10: [1. 2. 3. 4. 5.]
Square: [ 100  400  900 1600 2500]
Greater than 25: [False False  True  True  True]


## 6. Broadcasting

Broadcasting is a NumPy feature that allows arithmetic operations between
arrays of compatible shapes without explicitly writing loops.

For example, when a scalar is used with an array, NumPy applies the
operation to every element of the array.

In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Add 5:")
print(arr + 5)

print("Multiply by 2:")
print(arr * 2)

print("Subtract 10:")
print(arr - 10)

Add 5:
[[15 25 35]
 [45 55 65]]
Multiply by 2:
[[ 20  40  60]
 [ 80 100 120]]
Subtract 10:
[[ 0 10 20]
 [30 40 50]]


In [ ]:
values = np.array([1, 2, 3])

print(arr + values)

[[11 22 33]
 [41 52 63]]


## 7. Reshape

reshape() changes the structure or shape of an array without changing
the actual values.

The total number of elements must remain the same.

For example:

6 elements can be reshaped into:
- (2, 3)
- (3, 2)
- (6, 1)

because each shape contains 6 elements.

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])

print("Original array:")
print(arr)

reshaped = arr.reshape(2, 3)

print("Reshaped array:")
print(reshaped)

print("New shape:", reshaped.shape)

Original array:
[10 20 30 40 50 60]
Reshaped array:
[[10 20 30]
 [40 50 60]]
New shape: (2, 3)


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])

reshaped = arr.reshape(3, 2)

print(reshaped)
print("Shape:", reshaped.shape)

[[10 20]
 [30 40]
 [50 60]]
Shape: (3, 2)


### Reshape Rule

The number of elements before and after reshaping must be the same.

Example:

2 × 3 = 6 → valid

3 × 2 = 6 → valid

4 × 2 = 8 → invalid for an array containing only 6 elements.

## 8. NumPy Statistical Functions

Important functions:

- np.mean() → calculates the average
- np.max() → finds the largest value
- np.min() → finds the smallest value
- np.sum() → calculates the total

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Sum:", np.sum(arr))

Mean: 30.0
Maximum: 50
Minimum: 10
Sum: 150


## 9. Filtering

Filtering is used to select elements that satisfy a condition.

Basic syntax:

array[condition]

For example:

arr[arr > 30]

This checks every element and returns the actual values for which
the condition is True.

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])

print("Greater than 30:")
print(arr[arr > 30])

print("Less than 40:")
print(arr[arr < 40])

print("Equal to 50:")
print(arr[arr == 50])

print("Greater than or equal to 30:")
print(arr[arr >= 30])

Greater than 30:
[40 50 60]
Less than 40:
[10 20 30]
Equal to 50:
[50]
Greater than or equal to 30:
[30 40 50 60]


## 10. Filtering with Multiple Conditions

NumPy allows multiple conditions.

Symbols:

& → AND
| → OR

Each condition should be placed inside parentheses.

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])

print("Greater than 20 AND less than 50:")
print(arr[(arr > 20) & (arr < 50)])

print("Less than 20 OR greater than 50:")
print(arr[(arr < 20) | (arr > 50)])

print("Greater than or equal to 30 AND less than or equal to 50:")
print(arr[(arr >= 30) & (arr <= 50)])

Greater than 20 AND less than 50:
[30 40]
Less than 20 OR greater than 50:
[10 60]
Greater than or equal to 30 AND less than or equal to 50:
[30 40 50]


## 11. Matrix Multiplication

Started learning matrix multiplication.

Key difference:

* → element-wise multiplication
@ → matrix multiplication

Matrix multiplication will be completed in the next session.

In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Element-wise multiplication:")
print(A * B)

print("Matrix multiplication:")
print(A @ B)

Element-wise multiplication:
[[ 5 12]
 [21 32]]
Matrix multiplication:
[[19 22]
 [43 50]]


## 12. NumPy Arrays vs Python Lists

Python lists are general-purpose collections.

NumPy arrays are designed for numerical computing.

NumPy supports vectorized operations, multidimensional arrays,
and mathematical operations directly.

For AI/ML and numerical datasets, NumPy is generally more efficient
and convenient than normal Python lists.

In [1]:
numbers = [10, 20, 30, 40, 50]

result = []

for number in numbers:
    result.append(number + 5)

print("Python list result:", result)

Python list result: [15, 25, 35, 45, 55]


In [3]:
import numpy as np
numbers = np.array([10, 20, 30, 40, 50])

print("NumPy result:", numbers + 5)

NumPy result: [15 25 35 45 55]


## 13. Day 2 Assessment

I completed a 10-question NumPy assessment.

Score: 9/10

Topics tested:
- shape
- size
- ndim
- slicing
- vectorized operations
- broadcasting
- filtering
- matrix multiplication
- reshape
- mean

Areas to revise:
- Difference between shape and size
- Slicing: start index is included and stop index is excluded

## Day 2 Summary

Today I learned the fundamentals of NumPy and practiced working with
arrays and numerical data.

Topics completed:
- NumPy arrays
- shape
- ndim
- size
- dtype
- Indexing
- Negative indexing
- Slicing
- Vectorized operations
- Broadcasting
- reshape()
- mean()
- max()
- min()
- sum()
- Filtering
- Multiple conditions
- Matrix multiplication
- NumPy vs Python lists

Assessment Score: 9/10

Next step:
Continue with the next day of the AI/ML Engineer 90-Day Journey.